-------------------------------------------------------------------
-- Criar e carregar a tabela Aeroportos da base Aeroportos                            --
-------------------------------------------------------------------

-------------------------------------------------------------------
-- Trocar,'>_   ,>.  .>,'>'  .-.>.0.
-------------------------------------------------------------------
-- Postgres e Oracle. executar direto no ISQL                    --
-------------------------------------------------------------------

create table Aeroportos (
    Sigla       char(5) NOT NULL,
    Descricao   varchar(100),
    Municipio   varchar(70) NOT NULL,
    UF          char(4),
    Pais        char(25),
    Continente  char(16)
    );


Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Cymx','Mirabel-Montreal Airport','Mirabel','N/I','Canadá','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Cyqb','Quebec Jean Lesage Intl','Quebec Jean Lesage Intl','N/I','Canadá','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Cyyz','Toronto','Toronto','N/I','Canadá','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Dgaa','Accra/Kotoka Intl','Accra/Kotoka Intl','N/I','Gana','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Diap','Abidjan','Abidjan','N/I','Costa do Marfim','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Dnmm','Lagos','Lagos','N/I','NigéRia','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Dtta','Carthage','Tunis','N/I','TuníSia','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Dxxx','Aeroporto Internacional Lomé-Tokoin','Lomé','N/I','Togo','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ebbr','Bruxelas','Bruxelas','N/I','Bélgica','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eblg','Liege','Liege','N/I','Bélgica','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddb','Berlin Schoenefeld','Berlin Schoenefeld','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddf','Frankfurt','Frankfurt','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddh','Hamburg','Hamburg','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddk','Koln-Bonn','Koln-Bonn','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddl','Dusseldorf','Dusseldorf','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddm','Munchen','Munchen','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddr','Saarbrucken','Saarbrucken','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddt','Berlin Tegel','Berlin Tegel','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eddv','Hannover','Hannover','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Edfh','Hahn','Hahn','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Edhi','Hamburg-Finkenwerder','Hamburg-Finkenwerder','N/I','Alemanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eggw','Luton','Luton','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eghl','Lasham','Lasham','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Egkk','Gatwick','Londres','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Egll','Londres','Londres','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Egpk','Prestwick','Prestwick','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Egss','Londres','Londres','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Egte','Exeter International Airport','Clyst-Honiton','N/I','Reino Unido','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Eham','Amsterdam','Amsterdam','N/I','Holanda','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ehbk','Amsterdam','Amsterdam','N/I','Holanda','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ehwo','Netherlands/Bergen','Netherlands/Bergen','N/I','Holanda','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ellx','Luxemburgo','Luxemburgo','N/I','Luxemburgo','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Engm','Oslo','Oslo','N/I','Noruega','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Epwa','Warsaw Okecie','Warsaw Okecie','N/I','PolôNia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Esgg','Goteborg','Goteborg','N/I','SuéCia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Fact','Cape Town','Cape Town','N/I','África do Sul','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Fajs','Johannesburg','Johannesburg','N/I','África do Sul','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Fale','King Shaka International Airport','La Mercy','N/I','África do Sul','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Faup','Upington','Upington','N/I','África do Sul','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Fawb','Wonderboom','Wonderboom','N/I','África do Sul','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Fgsl','Malabo International Airport','Malabo','N/I','Guiné Equatorial','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Fnlu','Luanda','Luanda','N/I','Angola','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gclp','Las Palmas','Las Palmas','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gcrr','Lanzarote/Ilhas Canarias','Lanzarote/Ilhas Canarias','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gcts','Tenerife','Tenerife','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gcxo','Tenerife','Tenerife','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Glcp','Cape Palmas Airport','Greenville','TO','LibéRia','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Glrb','Monrovia','Monrovia','N/I','LibéRia','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gmad','Agadir/ Al Masslra','Agadir/ Al Masslra','N/I','Marrocos','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gmmn','Casablanca','Casablanca','N/I','Marrocos','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gmmx','Marrakech/Menara','Marrakech/Menara','N/I','Marrocos','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gooy','Dacar','Dacar','N/I','Senegal','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gucy','Conakry/Gbessia','Conakry/Gbessia','N/I','Guiné','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gvac','Ilha do Sal','Ilha do Sal','N/I','Cabo Verde','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gvfm','Francisco Mendes','Francisco Mendes','N/I','Cabo Verde','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Gvnp','Cabo Verde','Cabo Verde','N/I','Cabo Verde','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Heca','Cairo','Cairo','N/I','Egito','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Hkjk','Jomo Kenyatta International Airport','Nairobi','N/I','QuêNia','África');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kadw','Camp Springs/Andrews Afb,Md','Camp Springs/Andrews Afb,Md','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Katl','Atlanta/Intl','Atlanta/Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kaus','Austin-Bergstrom International Airport','Austin','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kbfi','Seattle Boeing F.Intl','Seattle Boeing F.Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kbna','Nashville International Airport','Nashville, Tennessee','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kbos','Boston','Boston','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kchs','Charleston','Charleston','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kclt','Charlotte Douglas Intl','Charlotte Douglas Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kdal','Dallas Love Field','Dallas','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kdfw','Dallas/Fort Worth','Dallas/Fort Worth','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kdov','Dover Air Force Base','Dover','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kdtw','Detroit','Detroit','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kelp','El Pasontl Ny','El Pasontl Ny','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kewr','Newark / Intl Nj','Newark / Intl Nj','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kfll','Fort Lauderdale','Fort Lauderdale','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kgso','Piedmont Triad Intl','Piedmont Triad Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kgtf','Great Falls International Airport','Great Falls','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kgyr','Phoenix Goodyear','Phoenix Goodyear','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Khou','Houston','Houston','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Khsv','Huntsville','Huntsville','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kiad','Washington/Dulles Intl','Washington/Dulles Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kiah','Houston','Houston','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kind','Indianapolis/Intl.In','Indianapolis/Intl.In','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kjax','Jacksonville/Intl.Fl.','Jacksonville/Intl.Fl.','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kjfk','New York','New York','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Klas','Las Vegas/Mccarran Intl','Las Vegas/Mccarran Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Klax','Los Angeles','Los Angeles','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Klcq','Lake City Muni','Lake City Muni','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Klit','Adams Field Airport','Little Rock','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kmco','Orlando','Orlando','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kmem','Menphis','Menphis','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kmia','Miami','Miami','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kmsy','New Orleans/Intl','New Orleans/Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kmzj','Pinal','Pinal','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kopf','Opa-Locka Airport','Dade','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kord','Chicago','Chicago','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kpae','Everett/Snohomish','Everett/Snohomish','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kpbi','Palm Beach Intl','Palm Beach Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kphl','Philadelphia-Intl','Philadelphia-Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Krfd','Chicago Rockford International Airport','Chicago','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Krme','Griffiss International Airport','Rome','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ksea','Seattle/Seattle-Tacoma Intl','Seattle/Seattle-Tacoma Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ksfb','Orlando Stanford International Airport','Stanford','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ksfo','San Francisco International Airport','San Francisco','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kstl','Lambert-St. Louis International Airport','St. Louis','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ktul','Tulsa/Intl','Tulsa/Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ktus','Tucson/Intl','Tucson/Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kvcv','Southern California Intl','Southern California Intl','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Kwri','Mc Guire Airport','Wrightstown','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lebl','Barcelona','Barcelona','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lemd','Madrid','Madrid','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lesa','Salamanca','Salamanca','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Leto','Madrid-Torrejon','Madrid-Torrejon','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Levc','Valencia','Valencia','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lezg','Zaragoza','Zaragoza','N/I','Espanha','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lfbd','Bordeaux','Bordeaux','N/I','FrançA','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lfbo','Toulouse/Blagnac','Toulouse/Blagnac','N/I','FrançA','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lfcf','Figeac','Figeac','N/I','FrançA','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lfpg','Paris','Paris','N/I','FrançA','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lfrd','Dinard-Pleurtuit-Saint-Malo Airport','Saint-Malo','N/I','FrançA','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lgat','Ellinikon Internacional Airport','Atenas','N/I','GréCia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lhbp','Budapeste','Budapeste','N/I','Hungria','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Limc','Milao','Milao','N/I','ItáLia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Limf','Torino/Caselle','Torino/Caselle','N/I','ItáLia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Limj','Genova','Genova','N/I','ItáLia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lirf','Roma','Roma','N/I','ItáLia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Llbg','Tel Aviv','Tel Aviv','N/I','Israel','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lpar','Alverca Ab','Alverca','N/I','Portugal','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lpfr','Faro / Madeira And Acores','Faro / Madeira And Acores','N/I','Portugal','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lppr','Porto','Porto','N/I','Portugal','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lppt','Lisboa','Lisboa','N/I','Portugal','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Lszh','Zurique','Zurique','N/I','SuíçA','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ltba','Istanbul/Ataturk','Istanbul/Ataturk','N/I','Turquia','Europa');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mdpc','Punta Cana','Punta Cana','N/I','República Dominicana','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mdsd','Sao Domingo/De Las Américas','Sao Domingo/De Las Américas','N/I','República Dominicana','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mggt','Guatemala/La Aurora','Guatemala/La Aurora','N/I','Guatemala','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mkjp','Kingston/Norman Manley Intl','Kingston/Norman Manley Intl','N/I','Jamaica','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmaa','Acapulco/Gen.Juan Alvarez','Acapulco/Gen.Juan Alvarez','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmgl','Guadalajara/Intl','Guadalajara/Intl','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmmd','Merida','Merida','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmmx','Mexico','Mexico','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmmy','Monterrey','Monterrey','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmtj','Tijuana','Tijuana','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmto','Toluca','Toluca','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mmun','Cancun/Intl','Cancun/Intl','N/I','MéXico','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mnmg','Managua','Managua','N/I','NicarÁgua','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mpto','Panama','Panama','N/I','Panamá','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mroc','San Jose/Juan Santamaria','San Jose/Juan Santamaria','N/I','Costa Rica','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mrsj','Airport San Jose Ciudad','San Jose','N/I','Costa Rica','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mslp','San Salvador','San Salvador','N/I','El Salvador','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mtpp','Port-De-Paix','Port-De-Paix','N/I','Haiti','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mucm','IgnáCio Agramonte Internationl Airport','Camaguey','N/I','Cuba','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Muha','Havana','Havana','N/I','Cuba','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Musc','Santa Clara','Santa Clara','N/I','Cuba','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Mynn','Nassau/Intl New Providence','Nassau/Intl New Providence','N/I','Bahamas','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Omaa','Ab Dhabi International','Ab Dhabi International','N/I','Emirados Árabes Unidos','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Omdb','Dubai International','Dubai International','N/I','Emirados Árabes Unidos','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Osdi','Damascus','Damascus','N/I','Síria, República Árabe','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Otbd','Doha International','Doha','N/I','Qatar','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Panc','Anchorage','Anchorage','N/I','Estados Unidos','América do Norte');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Rjaa','Tokio','Tokio','N/I','Japão','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Rksi','Inchon Intl','Inchon Intl','N/I','CoréIa do Sul','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Rkss','Gimpo Intl','Seul','N/I','CoréIa do Sul','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Saar','Rosário','Rosário','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sabe','Buenos Aires/Aeroparque','Buenos Aires/Aeroparque','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Saco','Cordoba','Cordoba','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Saez','Buenos Aires','Buenos Aires','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Saig','Iguazu','Iguazu','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Same','Mendoza','Mendoza','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Samm','Malargue,Mza','Malargue,Mza','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Samq','Mendoza, Mza','Mendoza, Mza','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sant','Tucuman/Ten Benjamiim Matie','Tucuman/Ten Benjamiim Matie','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sare','Resistencia','Resistencia','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sari','Iguazu','Iguazu','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sasa','Salta,S','Salta,S','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Saze','Pigue','Pigue','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sazn','Neuquen','Neuquen','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sazs','San Carlos de Bariloche','San Carlos de Bariloche','N/I','Argentina','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbaa','Conceição do Araguaia','Conceição do Araguaia','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbae','Bauru/Arealva','Arealva','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbaf','Campo Dos Afonsos','Rio de Janeiro','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbag','Angra Dos Reis','Angra Dos Reis','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbam','Amapá','Amapá','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sban','Base Aerea de Anapolis','AnáPolis','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbaq','Bartolomeu de Gusmão','Araraquara','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbar','Santa Maria','Aracaju','SE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbas','Marcelo Pires Halzhausen','Assis','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbat','Deputado Benedito Santiago','Alta Floresta','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbau','Estadual Dario Guarita','AraçAtuba','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbav','Usina Porto Primavera','Teodoro Sampaio','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbax','Romeu Zema','Araxá','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbe','Val de Cans','BeléM','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbg','Comandante Gustavo Kraemer','Bagé','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbh','Pampulha - Carlos Drummond de Andrade','Belo Horizonte','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbi','Bacacheri','Curitiba','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbq','Major Brigadeiro do Ar Doorgal Gomes','Barbacena','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbr','Presidente Juscelino Kubitschek','BrasíLia','DF','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbt','Chafei Amsei','Barretos','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbu','Bauru','Bauru','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbv','Atlas Brasil Cantanhede','Boa Vista','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbw','Barra do GarçAs','Barra do GarçAs','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbbz','Umberto Modiano','Armação dos Búzios','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbca','Adalberto Mendes da Silva','Cascavel','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcb','Cabo Frio','Cabo Frio','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcc','Cachimbo','Novo Progresso','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcd','Carlos Alberto da Costa Neves','CaçAdor','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcf','Tancredo Neves','Confins','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcg','Campo Grande','Campo Grande','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbch','Serafin Enoss Bertaso','Chapecó','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbci','Brigadeiro Lysias Augusto Rodrigues','Carolina','MA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcj','CarajáS','Parauapebas','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcm','DiomíCio Freitas','Forquilhinha','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcn','Nelson Rodrigues GuimarãEs','Caldas Novas','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbco','Canoas','Canoas','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcp','Bartolomeu Lisandro','Campos Dos Goytacazes','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcr','Corumbá','Corumbá','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbct','Afonso Pena','São José Dos Pinhais','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcv','Caravelas','Caravelas','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcx','Regional Hugo Cantergiani','Caxias do Sul','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcy','Marechal Rondon','Várzea Grande','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbcz','Cruzeiro do Sul','Cruzeiro do Sul','AC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbdb','Bonito','Bonito','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbdn','Presidente Prudente','Presidente Prudente','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbdo','Municipal Francisco de Matos Pereira','Dourados','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbeg','Eduardo Gomes','Manaus','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbek','Jacareacanga','Jacareacanga','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbfc','Franca','Franca','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbfi','Cataratas','Foz do Iguaçu','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbfl','HercíLio Luz','FlorianóPolis','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbfn','Fernando de Noronha','Fernando de Noronha','PE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbfz','Pinto Martins','Fortaleza','CE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgl','Aeroporto Internacional do Rio de Janeiro/Galeão – Antonio Carlos Jobim','Rio de Janeiro','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgm','Guajará-Mirim','Guajará-Mirim','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgo','Santa Genoveva','Goiânia','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgr','Guarulhos - Governador André Franco Montoro','Guarulhos','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgs','Ponta Grossa','Ponta Grossa','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgu','Tancredo Thomas de Faria','Guarapuava','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbgv','Coronel Altino Machado','Governador Valadares','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbht','Altamira','Altamira','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbic','Itacoatiara','Itacoatiara','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbih','Itaituba','Itaituba','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbil','Bahia - Jorge Amado','IlhéUs','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbip','Usiminas','Santana do ParaíSo','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbiz','Prefeito Renato Moreira','Imperatriz','MA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbjc','JúLio Cesar','BeléM','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbjf','Francisco de Assis','Juiz de Fora','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbji','Ji-Paraná','Ji-Paraná','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbjp','Presidente Castro Pinto','Bayeux','PB','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbjr','Jacarepaguá/Rj - Roberto Marinho','Rio de Janeiro','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbju','Orlando Bezerra de Menezes','Juazeiro do Norte','CE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbjv','Lauro Carneiro de Loyola','Joinville','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbkg','Presidente João Suassuna','Campina Grande','PB','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbkp','Viracopos','Campinas','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sble','HoráCio de Mattos','LençóIs','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sblj','Correia Pinto','Lages','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbln','Governador Lucas Nogueira Garcez','Lins','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sblo','Governador José Richa','Londrina','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sblp','Bom Jesus da Lapa','Bom Jesus da Lapa','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbls','Lagoa Santa','Lagoa Santa','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbma','Marabá','Marabá','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmc','Minaçu','Minaçu','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmd','Monte Dourado','Almeirim','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbme','Macaé','Macaé','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmg','Regional de Maringá - SíLvio Name JúNior','Maringá','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmh','Maringá','Maringá','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmk','Mário Ribeiro','Montes Claros','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbml','Frank Miloye Milenkovich','MaríLia','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmn','Ponta Pelada','Manaus','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmo','Zumbi Dos Palmares','Rio Largo','AL','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmq','Macapá','Macapá','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbms','Dix-Sept Rosado','Mossoró','RN','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmt','Campo de Marte','São Paulo','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbmy','Manicoré','Manicoré','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbnf','Ministro Victor Konder','Navegantes','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbnm','Santo ângelo','Santo ângelo','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbnt','Augusto Severo','Parnamirim','RN','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sboi','Oiapoque','Oiapoque','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpa','Salgado Filho','Porto Alegre','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpb','Prefeito Doutor João Silva Filho','ParnaíBa','PI','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpc','Embaixador Walther Moreira Salles','PoçOs de Caldas','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpf','Lauro Kurtz','Passo Fundo','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpj','Brigadeiro Lysias Rodrigues','Palmas','TO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpk','Pelotas','Pelotas','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpl','Senador Nilo Coelho','Petrolina','PE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpm','Palmas','Palmas','TO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpn','Porto Nacional','Porto Nacional','TO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpp','Ponta Porã','Ponta Porã','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbps','Porto Seguro','Porto Seguro','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbpv','Governador Jorge Teixeira de Oliveira','Porto Velho','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbqv','VitóRia da Conquista','VitóRia da Conquista','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbrb','PláCido de Castro','Sena Madureira','AC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbrf','Guararapes - Gilberto Freyre','Recife','PE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbrg','Rio Grande','Rio Grande','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbrj','Santos Dumont','Rio de Janeiro','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbrp','Leite Lopes','Ribeirão Preto','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsc','Bartolomeu de Gusmao','Rio de Janeiro','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsj','Professor Urbano Ernesto Stumpf','São José Dos Campos','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsl','Marechal Cunha Machado','São LuíS','MA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsm','Santa Maria','Santa Maria','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsn','Maestro Wilson Fonseca','SantaréM','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsp','Congonhas','São Paulo','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsr','Professor Eriberto Manoel Reino','São José do Rio Preto','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbst','Base Aerea','Santos','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbsv','Deputado LuíS Eduardo MagalhãEs','Salvador','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtb','Trombetas','Oriximiná','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtc','Hotel TransAmérica','Una','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtd','LuíS Dal Canalle Filho','Toledo','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbte','Senador PetrôNio Portella','Teresina','PI','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtf','Tefé','Tefé','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtk','Tarauacá','Tarauacá','AC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtl','TelêMaco Borba','TelêMaco Borba','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtr','Torres','Torres','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbts','Tirios','óBidos','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtt','Tabatinga','Tabatinga','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtu','Tucuruí','Tucuruí','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbtv','Terravista','Porto Seguro','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbua','São Gabriel da Cachoeira','São Gabriel da Cachoeira','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('SbUF','Paulo Afonso','Paulo Afonso','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbug','Rubem Berta','Uruguaiana','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbul','Tenente-Coronel Aviador CéSar Bombonato','Uberlândia','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbur','Mário de Almeida Franco','Uberaba','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbuy','Urucu','Coari','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbvg','Major Brigadeiro Trompowsky','Varginha','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbvh','Brigadeiro Camarão','Vilhena','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbvt','Eurico de Aguiar Salles','VitóRia','ES','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbys','Campo Fontenelle/Academia da ForçA AéRea','Pirassununga','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sbzm','Regional da Zona da Mata','Goianá','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Scar','Aeroporto Internacional de Chacalluta','Arica','N/I','Chile','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Scda','Iquique','Iquique','N/I','Chile','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Scel','Santiago do Chile','Santiago do Chile','N/I','Chile','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Scfa','Cerro Moreno','Antofagasta','N/I','Chile','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Scie','Concepcion/Carriel Sur','Concepcion/Carriel Sur','N/I','Chile','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Scti','Santiago Los Cerillos','Santiago Los Cerillos','N/I','Chile','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdag','Angra Dos Reis','Angra Dos Reis','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdcg','Senadora Eunice Michiles','São Paulo de OlivençA','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdco','Sorocaba','Sorocaba','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdlk','Caculé','Caculé','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdmc','Maricá','Maricá','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdou','Ourinhos','Ourinhos','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdov','Mozarlândia','Mozarlândia','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdow','Ourilândia do Norte','Ourilândia do Norte','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdpa','Faz. Porto Belo','Mangaratiba','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdrs','Resende','Resende','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdsc','Mário Pereira Lopes','São Carlos','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdtk','Paraty, Parati','Paraty','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdub','Gastão Madeira','Ubatuba','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdun','Itaperuna','Itaperuna','RJ','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sdvg','Domingos Pignatari','Votuporanga','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Segu','Guayaquil','Guayaquil','N/I','Equador','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Selt','Latacunga','Latacunga','N/I','Equador','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sequ','Quito','Quito','N/I','Equador','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sgas','Assuncao','Assuncao','N/I','Paraguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sges','Aeroporto Del Este','Aeroporto Del Este','N/I','Paraguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sibu','Catolé do Rocha','Catolé do Rocha','PB','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sifv','Aracruz','Aracruz','ES','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sigp','Gaviao Peixoto','Gavião Peixoto','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sikc','Colider','ColíDer','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Silc','Lucas do Rio Verde','Lucas do Rio Verde','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Silj','Laranjal do Jari','Laranjal do Jari','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Simk','Tenente Lund Presetto','Franca','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Siso','Fazenda Santo Ambrosio','Chaves','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sixe','Aeroclube de Eldorado do Sul','Eldorado do Sul','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sizx','Juara Sul','Juara','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjcw','Jatapu','Urucará','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjhg','Confresa','Confresa','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjkb','Cotriguacu','Cotriguaçu','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjlm','Leão de Ouro','Pacaraima','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjlu','Missao Catrimani','Caracaraí','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjnp','Novo Progresso','Novo Progresso','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjqk','Barra do Vento','Boa Vista','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjrg','Rio Grande','Rio Grande','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjtc','Moussa Nakhl Tobias','Arealva','SP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sjvo','AragarçAs','AragarçAs','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Skbo','Bogota','Bogota','N/I','ColôMbia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Skbq','Barranquilla','Barranquilla','N/I','ColôMbia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Skcl','Cali','Cali','N/I','ColôMbia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Skmd','Medellin/Olaya Herrera','Medellin/Olaya Herrera','N/I','ColôMbia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Skrg','Rio Negro/Jose Maria Cordov','Rio Negro/Jose Maria Cordov','N/I','ColôMbia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Slcb','Cochabamba','Cochabamba','N/I','BolíVia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sllp','La Paz','La Paz','N/I','BolíVia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Slps','Puerto Suarez','Puerto Suarez','N/I','BolíVia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Slvr','Viru Viru','Viru Viru','N/I','BolíVia','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Smjp','Zandery','Zandery','N/I','Suriname','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Smpb','Paramaribo','Paramaribo','N/I','Suriname','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snab','Araripina','Araripina','PE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snah','Adustina','Adustina','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snat','Aracati','Aracati','CE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snba','Asa Branca','Tartarugalzinho','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snbi','Bacabal','Bacabal','MA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snbr','Barreiras','Barreiras','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snbs','Balsas','Balsas','MA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snbu','Brumado','Brumado','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snbv','Campo de Boi','Ipixuna do Pará','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snbw','Baião','Baião','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sncb','Campo de Boi','Ipixuna do Pará','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sncc','CalçOene','CalçOene','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snci','Cibrasa','Capanema','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sndb','RuróPolis','RuróPolis','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sndc','Redenção','Redenção','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sndr','Domingos Rego','Timon','MA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sndt','Diamantina','Diamantina','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sndv','Brigadeiro Cabral','DivinóPolis','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sneb','Paragominas','Paragominas','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snfe','Comandante Paschoal Patrocínio Filho','Alfenas','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snfx','São Félix do Xingu','São Félix do Xingu','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sngi','Guanambi','Guanambi','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sngv','Governador Valadares','Governador Valadares','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snig','Iguatu','Iguatu','CE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snjb','Jacobina','Jacobina','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snjd','João Durval Carneiro','Feira de Santana','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snjk','Jequié','Jequié','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snjr','São João Del Rei','São João Del Rei','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snkb','Aeroclube','Campina Grande','PB','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snke','Santana do Araguaia','Santana do Araguaia','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snki','Cachoeiro de Itapemirim','Cachoeiro de Itapemirim','ES','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snkk','Caicó','Caicó','RN','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snla','Agropecuaria Umuarama','Parauapebas','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snma','Monte Alegre','Monte Alegre','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snmd','Mundico Coelho','Itaituba','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snmk','Mocambinho','JaíBa','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snml','Manduca Leao','Rio Largo','AL','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snmu','Mucuri','Mucuri','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snmx','São Mateus','São Mateus','ES','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snmz','Porto de Moz','Porto de Moz','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snnc','Rio Capim','Ipixuna do Pará','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snng','Progresso','Novo Progresso','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snnt','Nova Ponte','Nova Ponte','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snob','VirgíLio TáVora','Sobral','CE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snox','Oriximiná','Oriximiná','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpc','Picos','Picos','PI','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpd','Patos de Minas','Patos de Minas','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpg','Porto Grande','Porto Grande','AP','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpj','Patrocínio','Patrocínio','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpv','Porto de Vila do Conde','Barcarena','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpx','Pirapora','Pirapora','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snpy','São Sebastião do ParaíSo','São Sebastião do ParaíSo','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snqd','Sousa','Sousa','PB','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snqg','Cangapara','Floriano','PI','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snqm','Queimadas','Queimadas','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snrb','Rosa Branca','Itaituba','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snru','Oscar Laranjeiras','Caruaru','PE','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snsh','Sao Jose','SantaréM','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snsm','SalinóPolis','SalinóPolis','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snsw','Soure','Soure','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sntf','Teixeira de Freitas','Teixeira de Freitas','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snti','óBidos','óBidos','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snto','Juscelino Kubitscheck','TeóFilo Otoni','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sntp','Agropalma','Tailândia','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snts','Peregrino Filho','Patos','PB','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snub','Ubá','Ubá','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snuc','Açu','Açu','RN','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snui','Araçuaí','Araçuaí','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snvb','ValençA','ValençA','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snvr','Aeroclube da Bahia','Vera Cruz','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snvs','Breves','Breves','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snvv','Valente','Valente','BA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snwr','Wilma Rebelo','Senador José PorfíRio','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snxl','Primavera','QuerêNcia','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snxw','Chaves','Chaves','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snya','Almeirim','Almeirim','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snyb','Tito Teixeira','Ituiutaba','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snyv','Fazenda Sococo','Moju','PA','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Snza','Pouso Alegre','Pouso Alegre','MG','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Soca','Caiena','Caiena','N/I','Guiana Francesa','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Spcl','Pucallpa','Pucallpa','N/I','Peru','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Spim','Lima','Lima','N/I','Peru','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Splp','Las Palmas','Las Palmas','N/I','Peru','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Spqt','Iquitos','Iquitos','N/I','Peru','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Spso','Pisco','Pisco','N/I','Peru','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Spzo','Cuzco','Cuzco','N/I','Peru','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssbb','Estrela Dalva','Bodoquena','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssbg','Aeroclube','Bento GonçAlves','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssbn','BeléM Novo','Porto Alegre','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sscc','Cacador','CaçAdor','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssck','Olavo Cecco Rigon','ConcóRdia','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sscr','Ruben Berta','Marechal Cândido Rondon','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssdo','Municipal Francisco de Matos Pereira','Dourados','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sser','Erechim','Erechim','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssfb','Aeroporto Paulo Abdala','Francisco Beltrão','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sshz','Walter BÜNdchen','Horizontina','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssij','Ijuí','Ijuí','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssja','Santa Terezinha','JoaçAba','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sskm','Geraldo Guias de Aquino','Campo Mourão','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sskw','Cacoal','Cacoal','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssls','Salto Santiago','Laranjeiras do Sul','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sslt','GaudêNcio Machado Ramos','Alegrete','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssnh','Novo Hamburgo','Novo Hamburgo','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssnm','Guarantã','Guarantã do Norte','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssoe','Hélio Wasum','São Miguel do Oeste','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sspb','Juvenal Loureiro Cardoso','Pato Branco','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sspg','Santos Dumont','Paranaguá','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sspk','Porecatu','Porecatu','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sssc','Santa Cruz do Sul','Santa Cruz do Sul','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sstd','Toledo','Toledo','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sstl','Aeroporto Regional Plínio Alarcon','Três Lagoas','MS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssum','Orlando de Carvalho','Umuarama','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssuw','Guarapuava','Guarapuava','PR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ssvi','ângelo Ponzoni','Videira','SC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sszr','Santa Rosa','Santa Rosa','RS','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Suls','Maldonado-Uruguai','Maldonado-Uruguai','N/I','Uruguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sumu','Montevideu','Montevideu','N/I','Uruguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Supe','Punta Del Este','Punta Del Este','N/I','Uruguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Surv','Intl Rivera','Intl Rivera','N/I','Uruguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Suso','Salto','Salto','N/I','Uruguai','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svbc','Barcelona','Barcelona','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svjc','Paraguana','Paraguana','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svmc','Maracaibo/La Chinita Intl.','Maracaibo/La Chinita Intl.','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svmg','Margarita','Margarita','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svmi','Caracas/Intl','Caracas/Intl','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svmt','Maturn,Monagas','Maturn,Monagas','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svpr','Guayana','Guayana','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Svva','Valencia/Intl','Valencia/Intl','N/I','Venezuela','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swae','Uaicas','Alto Alegre','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swbc','Barcelos','Barcelos','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swbi','Barreirinha','Barreirinha','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swbr','Borba','Borba','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swbu','Fazenda Fartura Baixao Novo','Peixoto de Azevedo','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swbv','Auaris','Amajari','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swbz','Jpo Sorriso','Sorriso','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swca','Carauari','Carauari','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swcb','Campos Belos','Campos Belos','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swci','Colniza','Aripuanã','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swcp','Campo Novo Dos Parecis','Campo Novo do Parecis','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swcq','Costa Marques','Costa Marques','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swdb','AeróDromo Fazenda Eldorado','Barra do GarçAs','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swdm','Diamantino','Diamantino','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swei','Eirunepé','Eirunepé','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swek','Canarana','Canarana','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sweu','Caracarai','Caracaraí','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swfj','Feijó','Feijó','AC','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swfn','Flores','Manaus','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swfx','São Félix do Araguaia','São Félix do Araguaia','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swgi','Gurupi','Gurupi','TO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swgn','Araguaína','Araguaína','TO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swgp','Palmeiras de Goiás','Palmeiras de Goiás','GO','Brasil','America do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swhg','Aeroporto de Santa Helena de Goiás','Santa Helena de Goiás','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swhp','Fazenda Olho Dagua','Água Boa','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swht','Francisco Correa da Cruz','Humaitá','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swii','Ipiranga','Santo AntôNio do Içá','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swiq','Minaçu','Minaçu','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swji','Ji-Paraná','Ji-Paraná','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swjn','Juína','Juína','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swjp','Bittencourt','Japurá','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swju','Juruena','Juruena','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swjw','Jataí','Jataí','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swkc','CáCeres','CáCeres','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swkk','Cacoal','Cacoal','RO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swkn','Caldas Novas','Caldas Novas','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swko','Coari','Coari','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swlb','Lábrea','Lábrea','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swlc','General Leite de Castro','Rio Verde','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swlv','Estancia Santo Antonio','Santo AntôNio do Leverger','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swmw','MauéS','MauéS','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swna','Novo Aripuanã','Novo Aripuanã','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swnk','Novo Campo','Boca do Acre','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swno','Nova Olinda do Norte','Nova Olinda do Norte','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swnq','Niquelândia','Niquelândia','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swns','AnáPolis','AnáPolis','GO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swob','Fonte Boa','Fonte Boa','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swow','Moura','Barcelos','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swpc','Pari-Cachoeira','São Gabriel da Cachoeira','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swpd','Pouso da Águia','Bonfim','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swpf','Pitinga','Presidente Figueiredo','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swpi','JúLio Bélem','Parintins','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swpj','Palmas','Palmas','TO','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swpq','Piraguassu','Porto Alegre do Norte','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swqr','Estância Montenegro','Boa Vista','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swrd','RondonóPolis','RondonóPolis','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swrp','Aripuana','Aripuanã','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swsi','Presidente João Batista Figueiredo','Sinop','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swsq','São Joaquim','São Gabriel da Cachoeira','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swtp','Tapuruquara','Santa Isabel do Rio Negro','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swts','Tangará da Serra','Tangará da Serra','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swtu','Fazenda Tucunare','Campo Novo do Parecis','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swuq','Surucucu Ou Surucuru','Alto Alegre','RR','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swuy','Urucu','Coari','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swvc','Vila Rica','Vila Rica','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swvr','Estancia Rosalia','Sinop','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swwd','Barcelos','Barcelos','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swxm','Regional Orlando Villas Boas','Matupá','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swxv','Xavantina','Nova Xavantina','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swyk','Fazenda Ilha Camargo','Poconé','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swyn','Prainha','Apuí','AM','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Swyy','Aeroporto Fazenda Nova Viena','Barra do Garças','MT','Brasil','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Sycj','Cheddi Jagan Intl','Cheddi Jagan Intl','N/I','Guiana','América do Sul');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tapa','V. C. Bird International Airport','St. John S','N/I','AntíGua E Barbuda','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tbpb','Bridgetown/Grantley Adams','Bridgetown/Grantley Adams','N/I','Barbados','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tfff','Fort-De-France Lamentin','Fort-De-France Lamentin','N/I','Martinique','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tffr','Pointe-A-Pitre Le Raizet','Pointe-A-Pitre Le Raizet','N/I','Antilhas Francesas','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tjbq','Rafael HernáNdez Airport','Aguadilla','N/I','Porto Rico','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tjsj','San Juan','San Juan','N/I','Porto Rico','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tnca','Aruba','Aruba','N/I','Antilhas Holandesas','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tncc','Curacao','Curacao','N/I','Antilhas Holandesas','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Tncm','Philipsburg/Prinses Juliana','Philipsburg/Prinses Juliana','N/I','Antilhas Holandesas','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ttpp','Port Of Spain','Port Of Spain','N/I','Trinidad E Tobago','América Central');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Uuee','Sheremetyevo','Moscou','N/I','RúSsia','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Uuww','Moscow Vnukovo','Moscow Vnukovo','N/I','RúSsia','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Vhhh','Hong Kong International Airport','Hong Kong','N/I','China','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Vrmm','Male','Male','N/I','Maldivas','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Wiii','Jakarta Soekarno Hatta','Jakarta Soekarno Hatta','N/I','IndonéSia','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Wssl','Singapore Seletar','Singapore Seletar','N/I','Singapura','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Wsss','Changi','Changi','N/I','Singapura','Ásia');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Ybcs','Cairns','Cairns','N/I','AustráLia','Oceania');
Insert Into Aeroportos(Sigla, Descricao, Municipio, UF, Pais, Continente) Values ('Zbaa','Beijing','Beijing','N/I','China','Ásia');

UPDATE aeroportos SET sigla=Upper(sigla);

SELECT Count(*) From Aeroportos;
